# Generated by Django 4.1.1 on 2022-09-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_rename_is_email_verified_user_is_mail_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_mail_verified',
            new_name='is_email_verified',
        ),
    ]
