# Generated by Django 4.1.1 on 2022-10-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeehouse',
            name='barista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coffeehouse',
            name='grinder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
