# Generated by Django 4.1.1 on 2022-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_house', '0002_coffeehouse_barista_coffeehouse_grinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeehouse',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coffeehouse',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
