# Generated by Django 4.1.1 on 2022-10-17 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_house', '0003_coffeehouse_coordinates_coffeehouse_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeehouse',
            old_name='coordinates',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='coffeehouse',
            name='bike_friendly',
        ),
        migrations.RemoveField(
            model_name='coffeehouse',
            name='celiac',
        ),
        migrations.RemoveField(
            model_name='coffeehouse',
            name='toasters',
        ),
        migrations.AddField(
            model_name='coffeehouse',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coffeehouse',
            name='price_rate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
