# Generated by Django 4.1.1 on 2022-10-19 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_house', '0004_rename_coordinates_coffeehouse_latitude_and_more'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='house',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_house.coffeehouse'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
